import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Footer from "./components/ui/footer/Footer";
import Header from "./components/ui/header/Header";
import PageContainer from "./components/ui/pageContainer/PageContainer";
import "./globals.css";
const poppinsFont = Poppins({
  weight: "600",
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={poppinsFont.className}>
        <PageContainer>
          <Header />
          {children}
        </PageContainer>
        <Footer />
      </body>
    </html>
  );
}
